/*
 * This source file was generated by the Gradle 'init' task
 */
package be.kuleuven;

public class App {

    public static void main(String[] args) {
        System.out.println("Nothing to see here, use the Tests");
    }

}

/*
TODO: Maak nieuwe branch waar stukken code met de [DEBUG]-tag aanwezig zijn.
TODO: Stel in de les vragen over stukken code met de [QUESTION]-tag.
*/
